name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio black mypy
    
    - name: Lint with black
      run: |
        black --check jmap_mcp/
    
    - name: Run unit tests
      run: |
        pytest tests/ -m "not integration" -v
    
    - name: Test package installation
      run: |
        pip install -e .
        python -c "import jmap_mcp; print('Package installed successfully')" 